[alias]
update-version = "run --bin update_version --release -q --"
uv = "update-version"
publish-docker = "run --bin publish_docker --release -q --"
docker-publish = "publish-docker"
dp = "publish-docker"