[package]
name = "ffnodes_server"
version = "0.1.0"
edition = "2024"
description = ""
authors = ["Drew Chase"]
license = "MIT"
repository = "https://github.com/Drew-Chase/FFNodes.git"
build = "build.rs"

[lib]
name = "ffnodes_server_lib"
path = "src/lib.rs"




[build-dependencies]
walkdir = "2.5.0"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
actix-web = "4"
actix-multipart = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tokio = { version = "1", features = ["sync", "time", "fs", "macros", "rt-multi-thread", "io-util", "signal", "process"] }
log = "0.4.22"
walkdir = "2.5.0"
anyhow = "1.0.100"
thiserror = { version = "2.0.17" }
#clap = { version = "4.5.52", features = ["derive", "unicode", "string", "usage", "error-context", "wrap_help", "suggestions", "help", "color"] }
sqlx = { version = "0.8.6", features = ["sqlite", "macros", "derive", "time", "chrono", "runtime-tokio"] }
serde_hash = { version = "0.1.3" }
ffmpeg = { path = "../ffmpeg" }
futures = { version = "0.3" }
futures-util = { version = "0.3" }
notify = { version = "6.1" }
uuid = { version = "1.11", features = ["v4", "serde"] }
actix-ws = { version = "0.3" }
chrono = { version = "0.4" }
indicatif = { version = "0.17" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = { version = "0.2" }
tracing-indicatif = { version = "0.3" }
async-stream = { version = "0.3" }
jsonwebtoken = { version = "9.3" }